// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package kind

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type Kind_clusterKindConfig struct {
	ApiVersion              string                            `pulumi:"apiVersion"`
	ContainerdConfigPatches []string                          `pulumi:"containerdConfigPatches"`
	Kind                    string                            `pulumi:"kind"`
	Networking              *Kind_clusterKindConfigNetworking `pulumi:"networking"`
	Nodes                   []Kind_clusterKindConfigNode      `pulumi:"nodes"`
}

// Kind_clusterKindConfigInput is an input type that accepts Kind_clusterKindConfigArgs and Kind_clusterKindConfigOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigInput` via:
//
//          Kind_clusterKindConfigArgs{...}
type Kind_clusterKindConfigInput interface {
	pulumi.Input

	ToKind_clusterKindConfigOutput() Kind_clusterKindConfigOutput
	ToKind_clusterKindConfigOutputWithContext(context.Context) Kind_clusterKindConfigOutput
}

type Kind_clusterKindConfigArgs struct {
	ApiVersion              pulumi.StringInput                       `pulumi:"apiVersion"`
	ContainerdConfigPatches pulumi.StringArrayInput                  `pulumi:"containerdConfigPatches"`
	Kind                    pulumi.StringInput                       `pulumi:"kind"`
	Networking              Kind_clusterKindConfigNetworkingPtrInput `pulumi:"networking"`
	Nodes                   Kind_clusterKindConfigNodeArrayInput     `pulumi:"nodes"`
}

func (Kind_clusterKindConfigArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfig)(nil)).Elem()
}

func (i Kind_clusterKindConfigArgs) ToKind_clusterKindConfigOutput() Kind_clusterKindConfigOutput {
	return i.ToKind_clusterKindConfigOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigArgs) ToKind_clusterKindConfigOutputWithContext(ctx context.Context) Kind_clusterKindConfigOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigOutput)
}

func (i Kind_clusterKindConfigArgs) ToKind_clusterKindConfigPtrOutput() Kind_clusterKindConfigPtrOutput {
	return i.ToKind_clusterKindConfigPtrOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigArgs) ToKind_clusterKindConfigPtrOutputWithContext(ctx context.Context) Kind_clusterKindConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigOutput).ToKind_clusterKindConfigPtrOutputWithContext(ctx)
}

// Kind_clusterKindConfigPtrInput is an input type that accepts Kind_clusterKindConfigArgs, Kind_clusterKindConfigPtr and Kind_clusterKindConfigPtrOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigPtrInput` via:
//
//          Kind_clusterKindConfigArgs{...}
//
//  or:
//
//          nil
type Kind_clusterKindConfigPtrInput interface {
	pulumi.Input

	ToKind_clusterKindConfigPtrOutput() Kind_clusterKindConfigPtrOutput
	ToKind_clusterKindConfigPtrOutputWithContext(context.Context) Kind_clusterKindConfigPtrOutput
}

type kind_clusterKindConfigPtrType Kind_clusterKindConfigArgs

func Kind_clusterKindConfigPtr(v *Kind_clusterKindConfigArgs) Kind_clusterKindConfigPtrInput {
	return (*kind_clusterKindConfigPtrType)(v)
}

func (*kind_clusterKindConfigPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Kind_clusterKindConfig)(nil)).Elem()
}

func (i *kind_clusterKindConfigPtrType) ToKind_clusterKindConfigPtrOutput() Kind_clusterKindConfigPtrOutput {
	return i.ToKind_clusterKindConfigPtrOutputWithContext(context.Background())
}

func (i *kind_clusterKindConfigPtrType) ToKind_clusterKindConfigPtrOutputWithContext(ctx context.Context) Kind_clusterKindConfigPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigPtrOutput)
}

type Kind_clusterKindConfigOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfig)(nil)).Elem()
}

func (o Kind_clusterKindConfigOutput) ToKind_clusterKindConfigOutput() Kind_clusterKindConfigOutput {
	return o
}

func (o Kind_clusterKindConfigOutput) ToKind_clusterKindConfigOutputWithContext(ctx context.Context) Kind_clusterKindConfigOutput {
	return o
}

func (o Kind_clusterKindConfigOutput) ToKind_clusterKindConfigPtrOutput() Kind_clusterKindConfigPtrOutput {
	return o.ToKind_clusterKindConfigPtrOutputWithContext(context.Background())
}

func (o Kind_clusterKindConfigOutput) ToKind_clusterKindConfigPtrOutputWithContext(ctx context.Context) Kind_clusterKindConfigPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Kind_clusterKindConfig) *Kind_clusterKindConfig {
		return &v
	}).(Kind_clusterKindConfigPtrOutput)
}

func (o Kind_clusterKindConfigOutput) ApiVersion() pulumi.StringOutput {
	return o.ApplyT(func(v Kind_clusterKindConfig) string { return v.ApiVersion }).(pulumi.StringOutput)
}

func (o Kind_clusterKindConfigOutput) ContainerdConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v Kind_clusterKindConfig) []string { return v.ContainerdConfigPatches }).(pulumi.StringArrayOutput)
}

func (o Kind_clusterKindConfigOutput) Kind() pulumi.StringOutput {
	return o.ApplyT(func(v Kind_clusterKindConfig) string { return v.Kind }).(pulumi.StringOutput)
}

func (o Kind_clusterKindConfigOutput) Networking() Kind_clusterKindConfigNetworkingPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfig) *Kind_clusterKindConfigNetworking { return v.Networking }).(Kind_clusterKindConfigNetworkingPtrOutput)
}

func (o Kind_clusterKindConfigOutput) Nodes() Kind_clusterKindConfigNodeArrayOutput {
	return o.ApplyT(func(v Kind_clusterKindConfig) []Kind_clusterKindConfigNode { return v.Nodes }).(Kind_clusterKindConfigNodeArrayOutput)
}

type Kind_clusterKindConfigPtrOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Kind_clusterKindConfig)(nil)).Elem()
}

func (o Kind_clusterKindConfigPtrOutput) ToKind_clusterKindConfigPtrOutput() Kind_clusterKindConfigPtrOutput {
	return o
}

func (o Kind_clusterKindConfigPtrOutput) ToKind_clusterKindConfigPtrOutputWithContext(ctx context.Context) Kind_clusterKindConfigPtrOutput {
	return o
}

func (o Kind_clusterKindConfigPtrOutput) Elem() Kind_clusterKindConfigOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfig) Kind_clusterKindConfig {
		if v != nil {
			return *v
		}
		var ret Kind_clusterKindConfig
		return ret
	}).(Kind_clusterKindConfigOutput)
}

func (o Kind_clusterKindConfigPtrOutput) ApiVersion() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfig) *string {
		if v == nil {
			return nil
		}
		return &v.ApiVersion
	}).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigPtrOutput) ContainerdConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfig) []string {
		if v == nil {
			return nil
		}
		return v.ContainerdConfigPatches
	}).(pulumi.StringArrayOutput)
}

func (o Kind_clusterKindConfigPtrOutput) Kind() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfig) *string {
		if v == nil {
			return nil
		}
		return &v.Kind
	}).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigPtrOutput) Networking() Kind_clusterKindConfigNetworkingPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfig) *Kind_clusterKindConfigNetworking {
		if v == nil {
			return nil
		}
		return v.Networking
	}).(Kind_clusterKindConfigNetworkingPtrOutput)
}

func (o Kind_clusterKindConfigPtrOutput) Nodes() Kind_clusterKindConfigNodeArrayOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfig) []Kind_clusterKindConfigNode {
		if v == nil {
			return nil
		}
		return v.Nodes
	}).(Kind_clusterKindConfigNodeArrayOutput)
}

type Kind_clusterKindConfigNetworking struct {
	ApiServerAddress  *string `pulumi:"apiServerAddress"`
	ApiServerPort     *int    `pulumi:"apiServerPort"`
	DisableDefaultCni *bool   `pulumi:"disableDefaultCni"`
	IpFamily          *string `pulumi:"ipFamily"`
	KubeProxyMode     *string `pulumi:"kubeProxyMode"`
	PodSubnet         *string `pulumi:"podSubnet"`
	ServiceSubnet     *string `pulumi:"serviceSubnet"`
}

// Kind_clusterKindConfigNetworkingInput is an input type that accepts Kind_clusterKindConfigNetworkingArgs and Kind_clusterKindConfigNetworkingOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigNetworkingInput` via:
//
//          Kind_clusterKindConfigNetworkingArgs{...}
type Kind_clusterKindConfigNetworkingInput interface {
	pulumi.Input

	ToKind_clusterKindConfigNetworkingOutput() Kind_clusterKindConfigNetworkingOutput
	ToKind_clusterKindConfigNetworkingOutputWithContext(context.Context) Kind_clusterKindConfigNetworkingOutput
}

type Kind_clusterKindConfigNetworkingArgs struct {
	ApiServerAddress  pulumi.StringPtrInput `pulumi:"apiServerAddress"`
	ApiServerPort     pulumi.IntPtrInput    `pulumi:"apiServerPort"`
	DisableDefaultCni pulumi.BoolPtrInput   `pulumi:"disableDefaultCni"`
	IpFamily          pulumi.StringPtrInput `pulumi:"ipFamily"`
	KubeProxyMode     pulumi.StringPtrInput `pulumi:"kubeProxyMode"`
	PodSubnet         pulumi.StringPtrInput `pulumi:"podSubnet"`
	ServiceSubnet     pulumi.StringPtrInput `pulumi:"serviceSubnet"`
}

func (Kind_clusterKindConfigNetworkingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfigNetworking)(nil)).Elem()
}

func (i Kind_clusterKindConfigNetworkingArgs) ToKind_clusterKindConfigNetworkingOutput() Kind_clusterKindConfigNetworkingOutput {
	return i.ToKind_clusterKindConfigNetworkingOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigNetworkingArgs) ToKind_clusterKindConfigNetworkingOutputWithContext(ctx context.Context) Kind_clusterKindConfigNetworkingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigNetworkingOutput)
}

func (i Kind_clusterKindConfigNetworkingArgs) ToKind_clusterKindConfigNetworkingPtrOutput() Kind_clusterKindConfigNetworkingPtrOutput {
	return i.ToKind_clusterKindConfigNetworkingPtrOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigNetworkingArgs) ToKind_clusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) Kind_clusterKindConfigNetworkingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigNetworkingOutput).ToKind_clusterKindConfigNetworkingPtrOutputWithContext(ctx)
}

// Kind_clusterKindConfigNetworkingPtrInput is an input type that accepts Kind_clusterKindConfigNetworkingArgs, Kind_clusterKindConfigNetworkingPtr and Kind_clusterKindConfigNetworkingPtrOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigNetworkingPtrInput` via:
//
//          Kind_clusterKindConfigNetworkingArgs{...}
//
//  or:
//
//          nil
type Kind_clusterKindConfigNetworkingPtrInput interface {
	pulumi.Input

	ToKind_clusterKindConfigNetworkingPtrOutput() Kind_clusterKindConfigNetworkingPtrOutput
	ToKind_clusterKindConfigNetworkingPtrOutputWithContext(context.Context) Kind_clusterKindConfigNetworkingPtrOutput
}

type kind_clusterKindConfigNetworkingPtrType Kind_clusterKindConfigNetworkingArgs

func Kind_clusterKindConfigNetworkingPtr(v *Kind_clusterKindConfigNetworkingArgs) Kind_clusterKindConfigNetworkingPtrInput {
	return (*kind_clusterKindConfigNetworkingPtrType)(v)
}

func (*kind_clusterKindConfigNetworkingPtrType) ElementType() reflect.Type {
	return reflect.TypeOf((**Kind_clusterKindConfigNetworking)(nil)).Elem()
}

func (i *kind_clusterKindConfigNetworkingPtrType) ToKind_clusterKindConfigNetworkingPtrOutput() Kind_clusterKindConfigNetworkingPtrOutput {
	return i.ToKind_clusterKindConfigNetworkingPtrOutputWithContext(context.Background())
}

func (i *kind_clusterKindConfigNetworkingPtrType) ToKind_clusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) Kind_clusterKindConfigNetworkingPtrOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigNetworkingPtrOutput)
}

type Kind_clusterKindConfigNetworkingOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigNetworkingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfigNetworking)(nil)).Elem()
}

func (o Kind_clusterKindConfigNetworkingOutput) ToKind_clusterKindConfigNetworkingOutput() Kind_clusterKindConfigNetworkingOutput {
	return o
}

func (o Kind_clusterKindConfigNetworkingOutput) ToKind_clusterKindConfigNetworkingOutputWithContext(ctx context.Context) Kind_clusterKindConfigNetworkingOutput {
	return o
}

func (o Kind_clusterKindConfigNetworkingOutput) ToKind_clusterKindConfigNetworkingPtrOutput() Kind_clusterKindConfigNetworkingPtrOutput {
	return o.ToKind_clusterKindConfigNetworkingPtrOutputWithContext(context.Background())
}

func (o Kind_clusterKindConfigNetworkingOutput) ToKind_clusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) Kind_clusterKindConfigNetworkingPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v Kind_clusterKindConfigNetworking) *Kind_clusterKindConfigNetworking {
		return &v
	}).(Kind_clusterKindConfigNetworkingPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingOutput) ApiServerAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNetworking) *string { return v.ApiServerAddress }).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingOutput) ApiServerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNetworking) *int { return v.ApiServerPort }).(pulumi.IntPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingOutput) DisableDefaultCni() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNetworking) *bool { return v.DisableDefaultCni }).(pulumi.BoolPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingOutput) IpFamily() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNetworking) *string { return v.IpFamily }).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingOutput) KubeProxyMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNetworking) *string { return v.KubeProxyMode }).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingOutput) PodSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNetworking) *string { return v.PodSubnet }).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingOutput) ServiceSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNetworking) *string { return v.ServiceSubnet }).(pulumi.StringPtrOutput)
}

type Kind_clusterKindConfigNetworkingPtrOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigNetworkingPtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**Kind_clusterKindConfigNetworking)(nil)).Elem()
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) ToKind_clusterKindConfigNetworkingPtrOutput() Kind_clusterKindConfigNetworkingPtrOutput {
	return o
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) ToKind_clusterKindConfigNetworkingPtrOutputWithContext(ctx context.Context) Kind_clusterKindConfigNetworkingPtrOutput {
	return o
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) Elem() Kind_clusterKindConfigNetworkingOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfigNetworking) Kind_clusterKindConfigNetworking {
		if v != nil {
			return *v
		}
		var ret Kind_clusterKindConfigNetworking
		return ret
	}).(Kind_clusterKindConfigNetworkingOutput)
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) ApiServerAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.ApiServerAddress
	}).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) ApiServerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfigNetworking) *int {
		if v == nil {
			return nil
		}
		return v.ApiServerPort
	}).(pulumi.IntPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) DisableDefaultCni() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfigNetworking) *bool {
		if v == nil {
			return nil
		}
		return v.DisableDefaultCni
	}).(pulumi.BoolPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) IpFamily() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.IpFamily
	}).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) KubeProxyMode() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.KubeProxyMode
	}).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) PodSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.PodSubnet
	}).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNetworkingPtrOutput) ServiceSubnet() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *Kind_clusterKindConfigNetworking) *string {
		if v == nil {
			return nil
		}
		return v.ServiceSubnet
	}).(pulumi.StringPtrOutput)
}

type Kind_clusterKindConfigNode struct {
	ExtraMounts          []Kind_clusterKindConfigNodeExtraMount       `pulumi:"extraMounts"`
	ExtraPortMappings    []Kind_clusterKindConfigNodeExtraPortMapping `pulumi:"extraPortMappings"`
	Image                *string                                      `pulumi:"image"`
	KubeadmConfigPatches []string                                     `pulumi:"kubeadmConfigPatches"`
	Role                 *string                                      `pulumi:"role"`
}

// Kind_clusterKindConfigNodeInput is an input type that accepts Kind_clusterKindConfigNodeArgs and Kind_clusterKindConfigNodeOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigNodeInput` via:
//
//          Kind_clusterKindConfigNodeArgs{...}
type Kind_clusterKindConfigNodeInput interface {
	pulumi.Input

	ToKind_clusterKindConfigNodeOutput() Kind_clusterKindConfigNodeOutput
	ToKind_clusterKindConfigNodeOutputWithContext(context.Context) Kind_clusterKindConfigNodeOutput
}

type Kind_clusterKindConfigNodeArgs struct {
	ExtraMounts          Kind_clusterKindConfigNodeExtraMountArrayInput       `pulumi:"extraMounts"`
	ExtraPortMappings    Kind_clusterKindConfigNodeExtraPortMappingArrayInput `pulumi:"extraPortMappings"`
	Image                pulumi.StringPtrInput                                `pulumi:"image"`
	KubeadmConfigPatches pulumi.StringArrayInput                              `pulumi:"kubeadmConfigPatches"`
	Role                 pulumi.StringPtrInput                                `pulumi:"role"`
}

func (Kind_clusterKindConfigNodeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfigNode)(nil)).Elem()
}

func (i Kind_clusterKindConfigNodeArgs) ToKind_clusterKindConfigNodeOutput() Kind_clusterKindConfigNodeOutput {
	return i.ToKind_clusterKindConfigNodeOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigNodeArgs) ToKind_clusterKindConfigNodeOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigNodeOutput)
}

// Kind_clusterKindConfigNodeArrayInput is an input type that accepts Kind_clusterKindConfigNodeArray and Kind_clusterKindConfigNodeArrayOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigNodeArrayInput` via:
//
//          Kind_clusterKindConfigNodeArray{ Kind_clusterKindConfigNodeArgs{...} }
type Kind_clusterKindConfigNodeArrayInput interface {
	pulumi.Input

	ToKind_clusterKindConfigNodeArrayOutput() Kind_clusterKindConfigNodeArrayOutput
	ToKind_clusterKindConfigNodeArrayOutputWithContext(context.Context) Kind_clusterKindConfigNodeArrayOutput
}

type Kind_clusterKindConfigNodeArray []Kind_clusterKindConfigNodeInput

func (Kind_clusterKindConfigNodeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Kind_clusterKindConfigNode)(nil)).Elem()
}

func (i Kind_clusterKindConfigNodeArray) ToKind_clusterKindConfigNodeArrayOutput() Kind_clusterKindConfigNodeArrayOutput {
	return i.ToKind_clusterKindConfigNodeArrayOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigNodeArray) ToKind_clusterKindConfigNodeArrayOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigNodeArrayOutput)
}

type Kind_clusterKindConfigNodeOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigNodeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfigNode)(nil)).Elem()
}

func (o Kind_clusterKindConfigNodeOutput) ToKind_clusterKindConfigNodeOutput() Kind_clusterKindConfigNodeOutput {
	return o
}

func (o Kind_clusterKindConfigNodeOutput) ToKind_clusterKindConfigNodeOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeOutput {
	return o
}

func (o Kind_clusterKindConfigNodeOutput) ExtraMounts() Kind_clusterKindConfigNodeExtraMountArrayOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNode) []Kind_clusterKindConfigNodeExtraMount { return v.ExtraMounts }).(Kind_clusterKindConfigNodeExtraMountArrayOutput)
}

func (o Kind_clusterKindConfigNodeOutput) ExtraPortMappings() Kind_clusterKindConfigNodeExtraPortMappingArrayOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNode) []Kind_clusterKindConfigNodeExtraPortMapping {
		return v.ExtraPortMappings
	}).(Kind_clusterKindConfigNodeExtraPortMappingArrayOutput)
}

func (o Kind_clusterKindConfigNodeOutput) Image() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNode) *string { return v.Image }).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNodeOutput) KubeadmConfigPatches() pulumi.StringArrayOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNode) []string { return v.KubeadmConfigPatches }).(pulumi.StringArrayOutput)
}

func (o Kind_clusterKindConfigNodeOutput) Role() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNode) *string { return v.Role }).(pulumi.StringPtrOutput)
}

type Kind_clusterKindConfigNodeArrayOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigNodeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Kind_clusterKindConfigNode)(nil)).Elem()
}

func (o Kind_clusterKindConfigNodeArrayOutput) ToKind_clusterKindConfigNodeArrayOutput() Kind_clusterKindConfigNodeArrayOutput {
	return o
}

func (o Kind_clusterKindConfigNodeArrayOutput) ToKind_clusterKindConfigNodeArrayOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeArrayOutput {
	return o
}

func (o Kind_clusterKindConfigNodeArrayOutput) Index(i pulumi.IntInput) Kind_clusterKindConfigNodeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Kind_clusterKindConfigNode {
		return vs[0].([]Kind_clusterKindConfigNode)[vs[1].(int)]
	}).(Kind_clusterKindConfigNodeOutput)
}

type Kind_clusterKindConfigNodeExtraMount struct {
	ContainerPath *string `pulumi:"containerPath"`
	HostPath      *string `pulumi:"hostPath"`
}

// Kind_clusterKindConfigNodeExtraMountInput is an input type that accepts Kind_clusterKindConfigNodeExtraMountArgs and Kind_clusterKindConfigNodeExtraMountOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigNodeExtraMountInput` via:
//
//          Kind_clusterKindConfigNodeExtraMountArgs{...}
type Kind_clusterKindConfigNodeExtraMountInput interface {
	pulumi.Input

	ToKind_clusterKindConfigNodeExtraMountOutput() Kind_clusterKindConfigNodeExtraMountOutput
	ToKind_clusterKindConfigNodeExtraMountOutputWithContext(context.Context) Kind_clusterKindConfigNodeExtraMountOutput
}

type Kind_clusterKindConfigNodeExtraMountArgs struct {
	ContainerPath pulumi.StringPtrInput `pulumi:"containerPath"`
	HostPath      pulumi.StringPtrInput `pulumi:"hostPath"`
}

func (Kind_clusterKindConfigNodeExtraMountArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (i Kind_clusterKindConfigNodeExtraMountArgs) ToKind_clusterKindConfigNodeExtraMountOutput() Kind_clusterKindConfigNodeExtraMountOutput {
	return i.ToKind_clusterKindConfigNodeExtraMountOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigNodeExtraMountArgs) ToKind_clusterKindConfigNodeExtraMountOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeExtraMountOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigNodeExtraMountOutput)
}

// Kind_clusterKindConfigNodeExtraMountArrayInput is an input type that accepts Kind_clusterKindConfigNodeExtraMountArray and Kind_clusterKindConfigNodeExtraMountArrayOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigNodeExtraMountArrayInput` via:
//
//          Kind_clusterKindConfigNodeExtraMountArray{ Kind_clusterKindConfigNodeExtraMountArgs{...} }
type Kind_clusterKindConfigNodeExtraMountArrayInput interface {
	pulumi.Input

	ToKind_clusterKindConfigNodeExtraMountArrayOutput() Kind_clusterKindConfigNodeExtraMountArrayOutput
	ToKind_clusterKindConfigNodeExtraMountArrayOutputWithContext(context.Context) Kind_clusterKindConfigNodeExtraMountArrayOutput
}

type Kind_clusterKindConfigNodeExtraMountArray []Kind_clusterKindConfigNodeExtraMountInput

func (Kind_clusterKindConfigNodeExtraMountArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Kind_clusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (i Kind_clusterKindConfigNodeExtraMountArray) ToKind_clusterKindConfigNodeExtraMountArrayOutput() Kind_clusterKindConfigNodeExtraMountArrayOutput {
	return i.ToKind_clusterKindConfigNodeExtraMountArrayOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigNodeExtraMountArray) ToKind_clusterKindConfigNodeExtraMountArrayOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeExtraMountArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigNodeExtraMountArrayOutput)
}

type Kind_clusterKindConfigNodeExtraMountOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigNodeExtraMountOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (o Kind_clusterKindConfigNodeExtraMountOutput) ToKind_clusterKindConfigNodeExtraMountOutput() Kind_clusterKindConfigNodeExtraMountOutput {
	return o
}

func (o Kind_clusterKindConfigNodeExtraMountOutput) ToKind_clusterKindConfigNodeExtraMountOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeExtraMountOutput {
	return o
}

func (o Kind_clusterKindConfigNodeExtraMountOutput) ContainerPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNodeExtraMount) *string { return v.ContainerPath }).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNodeExtraMountOutput) HostPath() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNodeExtraMount) *string { return v.HostPath }).(pulumi.StringPtrOutput)
}

type Kind_clusterKindConfigNodeExtraMountArrayOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigNodeExtraMountArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Kind_clusterKindConfigNodeExtraMount)(nil)).Elem()
}

func (o Kind_clusterKindConfigNodeExtraMountArrayOutput) ToKind_clusterKindConfigNodeExtraMountArrayOutput() Kind_clusterKindConfigNodeExtraMountArrayOutput {
	return o
}

func (o Kind_clusterKindConfigNodeExtraMountArrayOutput) ToKind_clusterKindConfigNodeExtraMountArrayOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeExtraMountArrayOutput {
	return o
}

func (o Kind_clusterKindConfigNodeExtraMountArrayOutput) Index(i pulumi.IntInput) Kind_clusterKindConfigNodeExtraMountOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Kind_clusterKindConfigNodeExtraMount {
		return vs[0].([]Kind_clusterKindConfigNodeExtraMount)[vs[1].(int)]
	}).(Kind_clusterKindConfigNodeExtraMountOutput)
}

type Kind_clusterKindConfigNodeExtraPortMapping struct {
	ContainerPort *int    `pulumi:"containerPort"`
	HostPort      *int    `pulumi:"hostPort"`
	ListenAddress *string `pulumi:"listenAddress"`
	Protocol      *string `pulumi:"protocol"`
}

// Kind_clusterKindConfigNodeExtraPortMappingInput is an input type that accepts Kind_clusterKindConfigNodeExtraPortMappingArgs and Kind_clusterKindConfigNodeExtraPortMappingOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigNodeExtraPortMappingInput` via:
//
//          Kind_clusterKindConfigNodeExtraPortMappingArgs{...}
type Kind_clusterKindConfigNodeExtraPortMappingInput interface {
	pulumi.Input

	ToKind_clusterKindConfigNodeExtraPortMappingOutput() Kind_clusterKindConfigNodeExtraPortMappingOutput
	ToKind_clusterKindConfigNodeExtraPortMappingOutputWithContext(context.Context) Kind_clusterKindConfigNodeExtraPortMappingOutput
}

type Kind_clusterKindConfigNodeExtraPortMappingArgs struct {
	ContainerPort pulumi.IntPtrInput    `pulumi:"containerPort"`
	HostPort      pulumi.IntPtrInput    `pulumi:"hostPort"`
	ListenAddress pulumi.StringPtrInput `pulumi:"listenAddress"`
	Protocol      pulumi.StringPtrInput `pulumi:"protocol"`
}

func (Kind_clusterKindConfigNodeExtraPortMappingArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (i Kind_clusterKindConfigNodeExtraPortMappingArgs) ToKind_clusterKindConfigNodeExtraPortMappingOutput() Kind_clusterKindConfigNodeExtraPortMappingOutput {
	return i.ToKind_clusterKindConfigNodeExtraPortMappingOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigNodeExtraPortMappingArgs) ToKind_clusterKindConfigNodeExtraPortMappingOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeExtraPortMappingOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigNodeExtraPortMappingOutput)
}

// Kind_clusterKindConfigNodeExtraPortMappingArrayInput is an input type that accepts Kind_clusterKindConfigNodeExtraPortMappingArray and Kind_clusterKindConfigNodeExtraPortMappingArrayOutput values.
// You can construct a concrete instance of `Kind_clusterKindConfigNodeExtraPortMappingArrayInput` via:
//
//          Kind_clusterKindConfigNodeExtraPortMappingArray{ Kind_clusterKindConfigNodeExtraPortMappingArgs{...} }
type Kind_clusterKindConfigNodeExtraPortMappingArrayInput interface {
	pulumi.Input

	ToKind_clusterKindConfigNodeExtraPortMappingArrayOutput() Kind_clusterKindConfigNodeExtraPortMappingArrayOutput
	ToKind_clusterKindConfigNodeExtraPortMappingArrayOutputWithContext(context.Context) Kind_clusterKindConfigNodeExtraPortMappingArrayOutput
}

type Kind_clusterKindConfigNodeExtraPortMappingArray []Kind_clusterKindConfigNodeExtraPortMappingInput

func (Kind_clusterKindConfigNodeExtraPortMappingArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Kind_clusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (i Kind_clusterKindConfigNodeExtraPortMappingArray) ToKind_clusterKindConfigNodeExtraPortMappingArrayOutput() Kind_clusterKindConfigNodeExtraPortMappingArrayOutput {
	return i.ToKind_clusterKindConfigNodeExtraPortMappingArrayOutputWithContext(context.Background())
}

func (i Kind_clusterKindConfigNodeExtraPortMappingArray) ToKind_clusterKindConfigNodeExtraPortMappingArrayOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeExtraPortMappingArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(Kind_clusterKindConfigNodeExtraPortMappingArrayOutput)
}

type Kind_clusterKindConfigNodeExtraPortMappingOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigNodeExtraPortMappingOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*Kind_clusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (o Kind_clusterKindConfigNodeExtraPortMappingOutput) ToKind_clusterKindConfigNodeExtraPortMappingOutput() Kind_clusterKindConfigNodeExtraPortMappingOutput {
	return o
}

func (o Kind_clusterKindConfigNodeExtraPortMappingOutput) ToKind_clusterKindConfigNodeExtraPortMappingOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeExtraPortMappingOutput {
	return o
}

func (o Kind_clusterKindConfigNodeExtraPortMappingOutput) ContainerPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNodeExtraPortMapping) *int { return v.ContainerPort }).(pulumi.IntPtrOutput)
}

func (o Kind_clusterKindConfigNodeExtraPortMappingOutput) HostPort() pulumi.IntPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNodeExtraPortMapping) *int { return v.HostPort }).(pulumi.IntPtrOutput)
}

func (o Kind_clusterKindConfigNodeExtraPortMappingOutput) ListenAddress() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNodeExtraPortMapping) *string { return v.ListenAddress }).(pulumi.StringPtrOutput)
}

func (o Kind_clusterKindConfigNodeExtraPortMappingOutput) Protocol() pulumi.StringPtrOutput {
	return o.ApplyT(func(v Kind_clusterKindConfigNodeExtraPortMapping) *string { return v.Protocol }).(pulumi.StringPtrOutput)
}

type Kind_clusterKindConfigNodeExtraPortMappingArrayOutput struct{ *pulumi.OutputState }

func (Kind_clusterKindConfigNodeExtraPortMappingArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]Kind_clusterKindConfigNodeExtraPortMapping)(nil)).Elem()
}

func (o Kind_clusterKindConfigNodeExtraPortMappingArrayOutput) ToKind_clusterKindConfigNodeExtraPortMappingArrayOutput() Kind_clusterKindConfigNodeExtraPortMappingArrayOutput {
	return o
}

func (o Kind_clusterKindConfigNodeExtraPortMappingArrayOutput) ToKind_clusterKindConfigNodeExtraPortMappingArrayOutputWithContext(ctx context.Context) Kind_clusterKindConfigNodeExtraPortMappingArrayOutput {
	return o
}

func (o Kind_clusterKindConfigNodeExtraPortMappingArrayOutput) Index(i pulumi.IntInput) Kind_clusterKindConfigNodeExtraPortMappingOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) Kind_clusterKindConfigNodeExtraPortMapping {
		return vs[0].([]Kind_clusterKindConfigNodeExtraPortMapping)[vs[1].(int)]
	}).(Kind_clusterKindConfigNodeExtraPortMappingOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigInput)(nil)).Elem(), Kind_clusterKindConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigPtrInput)(nil)).Elem(), Kind_clusterKindConfigArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigNetworkingInput)(nil)).Elem(), Kind_clusterKindConfigNetworkingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigNetworkingPtrInput)(nil)).Elem(), Kind_clusterKindConfigNetworkingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigNodeInput)(nil)).Elem(), Kind_clusterKindConfigNodeArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigNodeArrayInput)(nil)).Elem(), Kind_clusterKindConfigNodeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigNodeExtraMountInput)(nil)).Elem(), Kind_clusterKindConfigNodeExtraMountArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigNodeExtraMountArrayInput)(nil)).Elem(), Kind_clusterKindConfigNodeExtraMountArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigNodeExtraPortMappingInput)(nil)).Elem(), Kind_clusterKindConfigNodeExtraPortMappingArgs{})
	pulumi.RegisterInputType(reflect.TypeOf((*Kind_clusterKindConfigNodeExtraPortMappingArrayInput)(nil)).Elem(), Kind_clusterKindConfigNodeExtraPortMappingArray{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigOutput{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigPtrOutput{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigNetworkingOutput{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigNetworkingPtrOutput{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigNodeOutput{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigNodeArrayOutput{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigNodeExtraMountOutput{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigNodeExtraMountArrayOutput{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigNodeExtraPortMappingOutput{})
	pulumi.RegisterOutputType(Kind_clusterKindConfigNodeExtraPortMappingArrayOutput{})
}
