// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Kind.Outputs
{

    [OutputType]
    public sealed class Kind_clusterKindConfigNode
    {
        public readonly ImmutableArray<Outputs.Kind_clusterKindConfigNodeExtraMount> ExtraMounts;
        public readonly ImmutableArray<Outputs.Kind_clusterKindConfigNodeExtraPortMapping> ExtraPortMappings;
        public readonly string? Image;
        public readonly ImmutableArray<string> KubeadmConfigPatches;
        public readonly string? Role;

        [OutputConstructor]
        private Kind_clusterKindConfigNode(
            ImmutableArray<Outputs.Kind_clusterKindConfigNodeExtraMount> extraMounts,

            ImmutableArray<Outputs.Kind_clusterKindConfigNodeExtraPortMapping> extraPortMappings,

            string? image,

            ImmutableArray<string> kubeadmConfigPatches,

            string? role)
        {
            ExtraMounts = extraMounts;
            ExtraPortMappings = extraPortMappings;
            Image = image;
            KubeadmConfigPatches = kubeadmConfigPatches;
            Role = role;
        }
    }
}
