// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface Kind_clusterKindConfig {
    apiVersion: pulumi.Input<string>;
    containerdConfigPatches?: pulumi.Input<pulumi.Input<string>[]>;
    kind: pulumi.Input<string>;
    networking?: pulumi.Input<inputs.Kind_clusterKindConfigNetworking>;
    nodes?: pulumi.Input<pulumi.Input<inputs.Kind_clusterKindConfigNode>[]>;
}

export interface Kind_clusterKindConfigNetworking {
    apiServerAddress?: pulumi.Input<string>;
    apiServerPort?: pulumi.Input<number>;
    disableDefaultCni?: pulumi.Input<boolean>;
    ipFamily?: pulumi.Input<string>;
    kubeProxyMode?: pulumi.Input<string>;
    podSubnet?: pulumi.Input<string>;
    serviceSubnet?: pulumi.Input<string>;
}

export interface Kind_clusterKindConfigNode {
    extraMounts?: pulumi.Input<pulumi.Input<inputs.Kind_clusterKindConfigNodeExtraMount>[]>;
    extraPortMappings?: pulumi.Input<pulumi.Input<inputs.Kind_clusterKindConfigNodeExtraPortMapping>[]>;
    image?: pulumi.Input<string>;
    kubeadmConfigPatches?: pulumi.Input<pulumi.Input<string>[]>;
    role?: pulumi.Input<string>;
}

export interface Kind_clusterKindConfigNodeExtraMount {
    containerPath?: pulumi.Input<string>;
    hostPath?: pulumi.Input<string>;
}

export interface Kind_clusterKindConfigNodeExtraPortMapping {
    containerPort?: pulumi.Input<number>;
    hostPort?: pulumi.Input<number>;
    listenAddress?: pulumi.Input<string>;
    protocol?: pulumi.Input<string>;
}
