// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "../types";

export interface Kind_clusterKindConfig {
    apiVersion: string;
    containerdConfigPatches?: string[];
    kind: string;
    networking?: outputs.Kind_clusterKindConfigNetworking;
    nodes?: outputs.Kind_clusterKindConfigNode[];
}

export interface Kind_clusterKindConfigNetworking {
    apiServerAddress?: string;
    apiServerPort?: number;
    disableDefaultCni?: boolean;
    ipFamily?: string;
    kubeProxyMode?: string;
    podSubnet?: string;
    serviceSubnet?: string;
}

export interface Kind_clusterKindConfigNode {
    extraMounts?: outputs.Kind_clusterKindConfigNodeExtraMount[];
    extraPortMappings?: outputs.Kind_clusterKindConfigNodeExtraPortMapping[];
    image?: string;
    kubeadmConfigPatches?: string[];
    role?: string;
}

export interface Kind_clusterKindConfigNodeExtraMount {
    containerPath?: string;
    hostPath?: string;
}

export interface Kind_clusterKindConfigNodeExtraPortMapping {
    containerPort?: number;
    hostPort?: number;
    listenAddress?: string;
    protocol?: string;
}

