// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import { input as inputs, output as outputs } from "./types";
import * as utilities from "./utilities";

export class Kind_cluster extends pulumi.CustomResource {
    /**
     * Get an existing Kind_cluster resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: Kind_clusterState, opts?: pulumi.CustomResourceOptions): Kind_cluster {
        return new Kind_cluster(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'kind:index/kind_cluster:kind_cluster';

    /**
     * Returns true if the given object is an instance of Kind_cluster.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Kind_cluster {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Kind_cluster.__pulumiType;
    }

    /**
     * Client certificate for authenticating to cluster.
     */
    public /*out*/ readonly clientCertificate!: pulumi.Output<string>;
    /**
     * Client key for authenticating to cluster.
     */
    public /*out*/ readonly clientKey!: pulumi.Output<string>;
    /**
     * Client verifies the server certificate with this CA cert.
     */
    public /*out*/ readonly clusterCaCertificate!: pulumi.Output<string>;
    /**
     * Kubernetes APIServer endpoint.
     */
    public /*out*/ readonly endpoint!: pulumi.Output<string>;
    /**
     * The kind_config that kind will use to bootstrap the cluster.
     */
    public readonly kindConfig!: pulumi.Output<outputs.Kind_clusterKindConfig | undefined>;
    /**
     * Kubeconfig set after the the cluster is created.
     */
    public /*out*/ readonly kubeconfig!: pulumi.Output<string>;
    /**
     * Kubeconfig path set after the the cluster is created or by the user to override defaults.
     */
    public readonly kubeconfigPath!: pulumi.Output<string>;
    /**
     * The kind name that is given to the created cluster.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The node_image that kind will use (ex: kindest/node:v1.15.3).
     */
    public readonly nodeImage!: pulumi.Output<string>;
    /**
     * Defines wether or not the provider will wait for the control plane to be ready. Defaults to false
     */
    public readonly waitForReady!: pulumi.Output<boolean | undefined>;

    /**
     * Create a Kind_cluster resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args?: Kind_clusterArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: Kind_clusterArgs | Kind_clusterState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as Kind_clusterState | undefined;
            resourceInputs["clientCertificate"] = state ? state.clientCertificate : undefined;
            resourceInputs["clientKey"] = state ? state.clientKey : undefined;
            resourceInputs["clusterCaCertificate"] = state ? state.clusterCaCertificate : undefined;
            resourceInputs["endpoint"] = state ? state.endpoint : undefined;
            resourceInputs["kindConfig"] = state ? state.kindConfig : undefined;
            resourceInputs["kubeconfig"] = state ? state.kubeconfig : undefined;
            resourceInputs["kubeconfigPath"] = state ? state.kubeconfigPath : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["nodeImage"] = state ? state.nodeImage : undefined;
            resourceInputs["waitForReady"] = state ? state.waitForReady : undefined;
        } else {
            const args = argsOrState as Kind_clusterArgs | undefined;
            resourceInputs["kindConfig"] = args ? args.kindConfig : undefined;
            resourceInputs["kubeconfigPath"] = args ? args.kubeconfigPath : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["nodeImage"] = args ? args.nodeImage : undefined;
            resourceInputs["waitForReady"] = args ? args.waitForReady : undefined;
            resourceInputs["clientCertificate"] = undefined /*out*/;
            resourceInputs["clientKey"] = undefined /*out*/;
            resourceInputs["clusterCaCertificate"] = undefined /*out*/;
            resourceInputs["endpoint"] = undefined /*out*/;
            resourceInputs["kubeconfig"] = undefined /*out*/;
        }
        if (!opts.version) {
            opts = pulumi.mergeOptions(opts, { version: utilities.getVersion()});
        }
        super(Kind_cluster.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * Input properties used for looking up and filtering kind_cluster resources.
 */
export interface Kind_clusterState {
    /**
     * Client certificate for authenticating to cluster.
     */
    clientCertificate?: pulumi.Input<string>;
    /**
     * Client key for authenticating to cluster.
     */
    clientKey?: pulumi.Input<string>;
    /**
     * Client verifies the server certificate with this CA cert.
     */
    clusterCaCertificate?: pulumi.Input<string>;
    /**
     * Kubernetes APIServer endpoint.
     */
    endpoint?: pulumi.Input<string>;
    /**
     * The kind_config that kind will use to bootstrap the cluster.
     */
    kindConfig?: pulumi.Input<inputs.Kind_clusterKindConfig>;
    /**
     * Kubeconfig set after the the cluster is created.
     */
    kubeconfig?: pulumi.Input<string>;
    /**
     * Kubeconfig path set after the the cluster is created or by the user to override defaults.
     */
    kubeconfigPath?: pulumi.Input<string>;
    /**
     * The kind name that is given to the created cluster.
     */
    name?: pulumi.Input<string>;
    /**
     * The node_image that kind will use (ex: kindest/node:v1.15.3).
     */
    nodeImage?: pulumi.Input<string>;
    /**
     * Defines wether or not the provider will wait for the control plane to be ready. Defaults to false
     */
    waitForReady?: pulumi.Input<boolean>;
}

/**
 * The set of arguments for constructing a Kind_cluster resource.
 */
export interface Kind_clusterArgs {
    /**
     * The kind_config that kind will use to bootstrap the cluster.
     */
    kindConfig?: pulumi.Input<inputs.Kind_clusterKindConfig>;
    /**
     * Kubeconfig path set after the the cluster is created or by the user to override defaults.
     */
    kubeconfigPath?: pulumi.Input<string>;
    /**
     * The kind name that is given to the created cluster.
     */
    name?: pulumi.Input<string>;
    /**
     * The node_image that kind will use (ex: kindest/node:v1.15.3).
     */
    nodeImage?: pulumi.Input<string>;
    /**
     * Defines wether or not the provider will wait for the control plane to be ready. Defaults to false
     */
    waitForReady?: pulumi.Input<boolean>;
}
